### PR TITLE
Set up mocha-chai-expect testing framework

### PR DESCRIPTION
**Pull request by mikeboyle**

### CODE REVIEW

**Comment by debryc** [comment]
While I do not have the know-how to review this code, I appreciate the work! Should I go ahead and merge it?

**Comment by mikeboyle** [comment]
@debryc Don't worry about this one. I assigned @monlu to look at it.

**Comment by monlu** [comment]
Looks fine to me!

**Comment by monlu** [comment]
@mikeboyle would you be interested in setting up a CI for this?

**Comment by mikeboyle** [comment]
@monlu yes! you mean like making the tests run on every pr?

**Pull request merged**
